call "C:\Users\Admin\Anaconda3\Scripts\activate.bat"
cd "C:\Users\Admin\tugas-akhir"
python elmo_wiki.py 11 16 "Atmosphere (architecture and spatial design)"
python elmo_wiki.py 16 21 "Atmosphere (architecture and spatial design)"
python elmo_wiki.py 21 26 "Atmosphere (architecture and spatial design)"
