call "C:\Users\Admin\Anaconda3\Scripts\activate.bat"
cd "C:\Users\Admin\tugas-akhir"
python elmo_wiki.py 67 72 "Atmosphere (architecture and spatial design)"
python elmo_wiki.py 72 77 "Atmosphere (architecture and spatial design)"
python elmo_wiki.py 77 82 "Atmosphere (architecture and spatial design)"
