call "C:\Users\Admin\Anaconda3\Scripts\activate.bat"
cd "C:\Users\Admin\tugas-akhir"
python elmo_wiki.py 22 27 "Atmosphere (architecture and spatial design)"
python elmo_wiki.py 27 32 "Atmosphere (architecture and spatial design)"
python elmo_wiki.py 32 37 "Atmosphere (architecture and spatial design)"
