call "C:\Users\Admin\Anaconda3\Scripts\activate.bat"
cd "C:\Users\Admin\tugas-akhir"
python elmo_wiki.py 0 5 "Atmosphere (architecture and spatial design)"
python elmo_wiki.py 5 10 "Atmosphere (architecture and spatial design)"
python elmo_wiki.py 10 15 "Atmosphere (architecture and spatial design)"
