call "C:\Users\Admin\Anaconda3\Scripts\activate.bat"
cd "C:\Users\Admin\tugas-akhir"
python elmo_wiki.py 30 35 "Drink"
python elmo_wiki.py 35 40 "Drink"
python elmo_wiki.py 40 45 "Drink"
python elmo_wiki.py 45 50 "Drink"
python elmo_wiki.py 50 55 "Drink"
python elmo_wiki.py 55 60 "Drink"
python elmo_wiki.py 60 65 "Drink"
