call "C:\Users\Admin\Anaconda3\Scripts\activate.bat"
cd "C:\Users\Admin\tugas-akhir"
python elmo_wiki.py 60 65 "Drink"
python elmo_wiki.py 65 70 "Drink"
python elmo_wiki.py 70 75 "Drink"
python elmo_wiki.py 75 80 "Drink"
python elmo_wiki.py 80 85 "Drink"
python elmo_wiki.py 85 90 "Drink"
python elmo_wiki.py 90 95 "Drink"
