call "C:\Users\Admin\Anaconda3\Scripts\activate.bat"
cd "C:\Users\Admin\tugas-akhir"
python elmo_wiki.py 0 5 "Drink"
python elmo_wiki.py 5 10 "Drink"
python elmo_wiki.py 10 15 "Drink"
python elmo_wiki.py 15 20 "Drink"
python elmo_wiki.py 20 25 "Drink"
python elmo_wiki.py 25 30 "Drink"
python elmo_wiki.py 30 35 "Drink"
