call "C:\Users\Admin\Anaconda3\Scripts\activate.bat"
cd "C:\Users\Admin\tugas-akhir"
python elmo_wiki.py 0 5 "Employment"
python elmo_wiki.py 5 10 "Employment"
python elmo_wiki.py 10 15 "Employment"
python elmo_wiki.py 15 20 "Employment"
python elmo_wiki.py 20 25 "Employment"
python elmo_wiki.py 25 30 "Employment"
