call "C:\Users\Admin\Anaconda3\Scripts\activate.bat"
cd "C:\Users\Admin\tugas-akhir"
python elmo_wiki.py 0 5 "Food"
python elmo_wiki.py 5 10 "Food"
python elmo_wiki.py 10 15 "Food"
python elmo_wiki.py 15 20 "Food"
python elmo_wiki.py 20 25 "Food"
python elmo_wiki.py 25 30 "Food"
python elmo_wiki.py 30 35 "Food"
python elmo_wiki.py 35 40 "Food"
python elmo_wiki.py 40 45 "Food"
python elmo_wiki.py 45 50 "Food"
python elmo_wiki.py 50 55 "Food"
python elmo_wiki.py 55 60 "Food"
python elmo_wiki.py 60 65 "Food"
