call "C:\Users\Admin\Anaconda3\Scripts\activate.bat"
cd "C:\Users\Admin\tugas-akhir"
python elmo_wiki.py 35 40 "Pricing"
python elmo_wiki.py 40 45 "Pricing"
python elmo_wiki.py 45 50 "Pricing"
python elmo_wiki.py 50 55 "Pricing"
python elmo_wiki.py 55 60 "Pricing"
python elmo_wiki.py 60 65 "Pricing"
python elmo_wiki.py 65 70 "Pricing"
python elmo_wiki.py 70 75 "Pricing"
