call "C:\Users\Admin\Anaconda3\Scripts\activate.bat"
cd "C:\Users\Admin\tugas-akhir"
python elmo_wiki.py 0 5 "Pricing"
python elmo_wiki.py 5 10 "Pricing"
python elmo_wiki.py 10 15 "Pricing"
python elmo_wiki.py 15 20 "Pricing"
python elmo_wiki.py 20 25 "Pricing"
python elmo_wiki.py 25 30 "Pricing"
python elmo_wiki.py 30 35 "Pricing"
python elmo_wiki.py 35 40 "Pricing"
