call "C:\Users\Admin\Anaconda3\Scripts\activate.bat"
cd "C:\Users\Admin\tugas-akhir"
python elmo_wiki.py 84 89 "Theme restaurant"
python elmo_wiki.py 89 94 "Theme restaurant"
python elmo_wiki.py 94 99 "Theme restaurant"
