call "C:\Users\Admin\Anaconda3\Scripts\activate.bat"
cd "C:\Users\Admin\tugas-akhir"
python elmo_wiki.py 56 61 "Theme restaurant"
python elmo_wiki.py 61 66 "Theme restaurant"
python elmo_wiki.py 66 71 "Theme restaurant"
