call "C:\Users\Admin\Anaconda3\Scripts\activate.bat"
cd "C:\Users\Admin\tugas-akhir"
python elmo_wiki.py 70 75 "Theme restaurant"
python elmo_wiki.py 75 80 "Theme restaurant"
python elmo_wiki.py 80 85 "Theme restaurant"
