call "C:\Users\Admin\Anaconda3\Scripts\activate.bat"
cd "C:\Users\Admin\tugas-akhir"
python elmo_wiki.py 0 5 "Theme restaurant"
python elmo_wiki.py 5 10 "Theme restaurant"
python elmo_wiki.py 10 15 "Theme restaurant"
